# Generated by Django 4.2.11 on 2025-06-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0003_remove_customer_address_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_body_water', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_fat_mass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skeletal_muscle_mass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('intracellular_fluid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extracellular_fluid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_mass_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_fat_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('basal_metabolic_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_app.customer')),
            ],
        ),
    ]
