# Generated by Django 4.2.11 on 2025-06-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0004_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='Height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='Weight',
            new_name='weight',
        ),
    ]
