# Generated by Django 4.2.11 on 2025-06-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0005_rename_height_progress_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='progress_pictures/'),
        ),
    ]
