# Generated by Django 4.2.11 on 2025-06-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0006_progress_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='progress_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
